name: github pages

on:
  push:
    branches:
      - master
    tags:
      - v*

env:
  RUST_VERSION: 1.63.0

jobs:
  deploy-contributing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.15"

      - run: mdbook build ./.docs/contributing-book

      - name: Deploy master
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.docs/contributing-book/book
          destination_dir: book
        if: github.ref == 'refs/heads/master'

  deploy-forc-doc-sway-libs:
    strategy:
      matrix:
        project:
          [
            "admin",
            "bytecode",
            "fixed_point",
            "merkle_proof",
            "native_asset",
            "ownership",
            "pausable",
            "queue",
            "reentrancy",
            "signed_integers",
          ]
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
      
      - uses: Swatinem/rust-cache@v2 
      - name: Install Forc
        run: cargo install --locked --debug --path ./forc
      
      - name: Install Forc plugins
        run: |
          cargo install --locked --debug --path ./forc-plugins/forc-doc
      
      - name: Build sway-libs docs
        run: |
          cd libs/${{ matrix.project }}
          forc doc

      - name: Deploy master std
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./libs/${{ matrix.project }}/out/doc
          destination_dir: master/${{ matrix.project }}
        if: github.ref == 'refs/heads/master'

      - name: Get tag
        id: branch_name
        run: |
          echo ::set-output name=BRANCH_NAME::${GITHUB_REF#refs/tags/}
        if: startsWith(github.ref, 'refs/tags')

      - name: Deploy std tag
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./libs/${{ matrix.project }}/out/doc
          destination_dir: ${{ steps.branch_name.outputs.BRANCH_NAME }}/${{ matrix.project }}
        if: startsWith(github.ref, 'refs/tags')
